image: gradle:6.8.3-jdk8

stages:
  - test

unit-test:
  stage: test
  needs: []
  script:
    - gradle unit_test
  artifacts:
    name: ${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    expire_in: 2 weeks
    paths:
      - build/
    reports:
      junit: build/test-report/junit.xml
      cobertura: build/coverage-report/cobertura-coverage.xml

lint:
  stage: test
  needs: []
  script:
    - gradle lint
  artifacts:
    name: ${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    expire_in: 2 weeks
    paths:
      - build/
    reports:
      junit: build/lint-report/eslint-junit.xml
